version: "3.7"
services:
  # app1, app2 and app3 are Caddy instances listening to port 80 and serving an index.html.
  app1:
    image: dockercloud/hello-world:latest
    networks:
      internal-network:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "app1.test"
    labels:
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:app1.test"

  app2:
    image: dockercloud/hello-world:latest
    networks:
      internal-network:
        aliases:
        - "app2.test"
    labels:
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:app2.test"

  app3:
    image: dockercloud/hello-world:latest
    networks:
      internal-network:
        aliases:
        - "app3.test"
    labels:
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:app3.test"

networks:
  # everything that is *only* on "internal network" cannot talk to WAN
  internal-network:
    internal: true